name: Build iOS
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Install dependencies
        run: |
          cd nas-material-manager
          flutter pub get
          cd ios
          pod repo update
          pod install

      - name: Build iOS
        run: |
          cd nas-material-manager
          flutter build ios --release --no-codesign

      - name: Upload iOS App
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: nas-material-manager/build/ios/iphoneos/
